### ISSUE TITLE
Always enable /replication handler

### ISSUE THREAD

**Issue by mberkowski** [BTAA-Geospatial-Data-Project/geoportal-solr-config#12]
We can just always keep a basic /replication handler enabled in solrconfig.xml. At a time when we had switching between cores and actual replication (not just backups) enabled on cores between geomg and geoportal, we had to turn on replication conditionally. Now it can just be there all the time:

```
<requestHandler name="/replication" class="solr.ReplicationHandler" startup="lazy" />
```

**Comment by akierig** [comment]
closed by #13
